server:
  port: 8098

spring:
  application:
    name: notification-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/nlmkend
    username: postgres
    password: 1
    properties:
      schema: notification
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: notification
    schemas: notification
    url: jdbc:postgresql://localhost:5432/nlmkend
  kafka:
    bootstrap-servers: localhost:9095
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      auto-commit: false
      max-poll-records: 1
      group-id: mail-sender
      properties:
        spring:
          json:
            trusted:
              packages: 'ru.danilarassokhin.*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual
      async-acks: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master

mail:
  timer: 300000
  batch-size: 10
  kafka:
    topic: mail.notification.000

soap:
  endpoints:
    get-all-mails: true